import 'package:logger/logger.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'package:eba/database/driver.dart';
import 'package:eba/database/login.dart';

class LoginForm extends StatefulWidget {
  @override
  _LoginFormState createState() => _LoginFormState();
}

class _LoginFormState extends State<LoginForm> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Color(0xffaad4aa),
      body: Column(
        children: <Widget>[
          Expanded(
            flex: 6,
            child: Container(
              color: Colors.white,
              child: Column(
                children: <Widget>[
                  Expanded(
                    flex: 1,
                    child: Container(),
                  ),
                  Divider(
                    indent: 30.0,
                    endIndent: 30.0,
                    thickness: 3.0,
                    height: 0.0,
                    color: Color(0xffaad4aa),
                  ),
                  Expanded(
                    flex: 4,
                    child: Container(
                      color: Colors.white,
                      padding: const EdgeInsets.only(left: 30.0, top: 8.0, right: 30.0, bottom: 0.0),
                      alignment: Alignment.topLeft,
                      child: Text(
                        'QUEREMOS\nSABER\nMÁS\nSOBRE\nTI',
                        style: TextStyle(
                          fontFamily: 'LeagueSpartan',
                          fontSize: 50.0,
                          color: Color(0xff363839),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
          Expanded(
            flex: 7,
            child: Column(
              children: <Widget>[
                Expanded(
                  flex: 1,
                  child: Container(
                    color: Color(0xffaad4aa),
                    alignment: Alignment.topCenter,
                    child: SizedBox(
                      width: double.infinity,
                      child: Image.asset('images/spilled-milk.png'),
                    ),
                  ),
                ),
                Expanded(
                  flex: 5,
                  child: LoginFormWidget(),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class LoginFormWidget extends StatefulWidget {
  @override
  _LoginFormWidgetState createState() => _LoginFormWidgetState();
}

class _LoginFormWidgetState extends State<LoginFormWidget> {
  final _formKey = GlobalKey<FormState>();

  Login _values = Login(age: 18, country: 'Colombia', department: 'Bogotá D.C.', city: 'Bogotá D.C.');
  List<String> _cities = [ 'Bogotá D.C.' ];
  bool _visible = true;

  @override
  Widget build(BuildContext context) {
    return Form(
        key: _formKey,
        child: Container(
          color: Color(0xffaad4aa),
          child: Column(
              children: <Widget>[
                Expanded(
                  flex: _visible ? 0 : 1,
                  child: Container(),
                ),
                Expanded(
                  flex: _visible ? 1 : 2,
                  child: buildFormFieldSelector(
                    label: '¿Cuál es tu edad?',
                    hint: 'Edad (en años)',
                    data: [ for (var i = 6; i < 100; i++) i.toString() ],
                    value: _values.age.toString(),
                    onChanged: (value) {
                      setState(() {
                        Logger().d('Set Age');
                        _values.age = int.parse(value);
                      });
                    }
                  ),
                ),
                Expanded(
                  flex: _visible ? 0 : 1,
                  child: Container(),
                ),
                Expanded(
                  flex: _visible ? 1 : 2,
                  child: buildFormFieldSelector(
                    label: '¿En qué país resides?',
                    hint: 'País de residencia',
                    data: countries,
                    value: _values.country,
                    onChanged: (value) {
                      setState(() {
                        Logger().d('Set Country');
                        _visible = value == 'Colombia';
                        _values.country = value;
                      });
                    },
                  ),
                ),
                Expanded(
                  flex: _visible ? 0 : 1,
                  child: Container(),
                ),
                Visibility(
                  visible: _visible,
                  child: Expanded(
                    flex: 1,
                    child: buildFormFieldSelector(
                      label: '¿En qué departamento?',
                      hint: 'Departamento de residencia',
                      data: departments,
                      value: _values.department,
                      onChanged: (value) {
                        setState(() {
                          Logger().d('Set Department');
                          _values.department = value;
                          _values.city = null;
                          _cities = citiesMap[value];
                          _values.city = _cities[0];
                        });
                      },
                    ),
                  ),
                ),
                Visibility(
                  visible: _visible,
                  child: Expanded(
                    flex: 1,
                    child: buildFormFieldSelector(
                      label: '¿Y en qué municipio?',
                      hint: 'Municipio de residencia',
                      data: _cities,
                      value: _values.city,
                      onChanged: (value) {
                        setState(() {
                          Logger().d('Set City');
                          _values.city = value;
                        });
                      },
                    ),
                  ),
                ),
                Expanded(
                    flex: _visible ? 1 : 2,
                    child: buildSubmitFormButton(() {
                      if (_formKey.currentState.validate()) {
                        Logger().d('Saving Login info in the database');
                        Driver().login(_values);
                        Logger().d('Going to Camera Request from Login Form');
                        Navigator.pushReplacementNamed(context, '/camera-request');
                      }
                    })
                ),
                Expanded(
                  flex: _visible ? 0 : 1,
                  child: Container(),
                ),
              ]
          ),
        )
    );
  }
}

Widget buildFormFieldSelector({String label, String hint, List<String> data, String value, Function onChanged}) => Row(
  children: <Widget>[
    Expanded(
      flex: 1,
      child: Container(),
    ),
    Expanded(
      flex: 8,
      child: Column(
        children: <Widget>[
          Expanded(
            flex: 5,
            child: Text(
              label,
              style: TextStyle(
                fontFamily: 'Canda Tawa Regular',
                color: Color(0xff363839),
                fontSize: 30.0,
                height: 1.3,
              ),
            ),
          ),
          Expanded(
            flex: 4,
            child: Container(
              alignment: Alignment.topCenter,
              color: Colors.white,
              child: DropdownButtonHideUnderline(
                child: new DropdownButton<String>(
                  value: value,
                  isExpanded: true,
                  style: TextStyle(
                    fontFamily: 'Canda Tawa Regular',
                    color: Color(0xff363839),
                    fontSize: 30.0,
                  ),
                  items: data.map((String value) {
                    return new DropdownMenuItem<String>(
                      value: value,
                      child: SizedBox(
                        width: double.infinity,
                        child: new Text(
                          value,
                          textAlign: TextAlign.center,
                        ),
                      ),
                    );
                  }).toList(),
                  onChanged: onChanged,
                ),
              ),
            ),
          )
        ],
      ),
    ),
    Expanded(
      flex: 1,
      child: Container(),
    ),
  ],
);

Widget buildSubmitFormButton(Function onPressedFunction) => Container(
  alignment: Alignment.bottomCenter,
  child: Row(
    children: <Widget>[
      Expanded(
        flex: 1,
        child: Container(),
      ),
      Expanded(
        flex: 2,
        child: Column(
          children: <Widget>[
            Expanded(
              flex: 2,
              child: Container(),
            ),
            Expanded(
              flex: 7,
              child: FlatButton(
                onPressed: onPressedFunction,
                child: Column(
                  children: <Widget>[
                    Text(
                      'CONTINUAR',
                      style: TextStyle(
                        fontFamily: 'LeagueSpartan',
                        color: Colors.white,
                        fontSize: 22.0,
                        letterSpacing: 1.5,
                      ),
                    ),
                    Container(
                      alignment: Alignment.topLeft,
                      padding: const EdgeInsets.only(left: 10.0, right: 10.0),
                      child: Image.asset('images/dashed-line.png'),
                    )
                  ],
                ),
              ),
            ),
            Expanded(
              flex: 2,
              child: Container(),
            ),
          ],
        ),
      ),
      Expanded(
        flex: 1,
        child: Container(),
      ),
    ],
  ),
);

final List<String> countries = <String>[
  'Colombia',
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Bangladés',
  'Barbados',
  'Baréin',
  'Belice',
  'Benín',
  'Bielorrusia',
  'Birmania',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Bután',
  'Bélgica',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'Catar',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Ciudad del Vaticano',
  'Comoras',
  'Corea del Norte',
  'Corea del Sur',
  'Costa Rica',
  'Costa de Marfil',
  'Croacia',
  'Cuba',
  'Curazao',
  'Dinamarca',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Escocia',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Etiopía',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabón',
  'Gales',
  'Gambia',
  'Georgia',
  'Ghana',
  'Granada',
  'Grecia',
  'Groenlandia',
  'Guatemala',
  'Guinea',
  'Guinea Ecuatorial',
  'Guinea-Bisáu',
  'Guyana',
  'Haití',
  'Honduras',
  'Hungría',
  'India',
  'Indonesia',
  'Inglaterra',
  'Irak',
  'Irlanda',
  'Irlanda del Norte',
  'Irán',
  'Islandia',
  'Islas Cook',
  'Islas Feroe',
  'Islas Marianas del Norte',
  'Islas Marshall',
  'Islas Salomón',
  'Israel',
  'Italia',
  'Jamaica',
  'Japón',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letonia',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Líbano',
  'Macedonia del Norte',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Mauricio',
  'Mauritania',
  'Micronesia',
  'Moldavia',
  'Mongolia',
  'Montenegro',
  'Mozambique',
  'México',
  'Mónaco',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Nigeria',
  'Niue',
  'Noruega',
  'Nueva Zelanda',
  'Níger',
  'Omán',
  'Pakistán',
  'Palaos',
  'Palestina',
  'Panamá',
  'Papúa Nueva Guinea',
  'Paraguay',
  'Países Bajos',
  'Perú',
  'Polonia',
  'Portugal',
  'Puerto Rico',
  'Reino Unido',
  'República Centroafricana',
  'República Checa',
  'República Democrática del Congo',
  'República Dominicana',
  'República del Congo',
  'Ruanda',
  'Rumania',
  'Rusia',
  'Samoa',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Martín',
  'San Vicente y las Granadinas',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Suazilandia',
  'Sudáfrica',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Tailandia',
  'Taiwán',
  'Tanzania',
  'Tayikistán',
  'Timor Oriental',
  'Togo',
  'Tonga',
  'Trinidad y Tobago',
  'Turkmenistán',
  'Turquía',
  'Tuvalu',
  'Túnez',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
];

final List<String> departments = <String>[
  'Bogotá D.C.',
  'Amazonas',
  'Antioquia',
  'Arauca',
  'Atlántico',
  'Bolívar',
  'Boyacá',
  'Caldas',
  'Caquetá',
  'Casanare',
  'Cauca',
  'Cesar',
  'Chocó',
  'Córdoba',
  'Cundinamarca',
  'Guainía',
  'Guaviare',
  'Huila',
  'La Guajira',
  'Magdalena',
  'Meta',
  'Nariño',
  'Norte de Santander',
  'Putumayo',
  'Quindío',
  'Risaralda',
  'San Andrés y Providencia',
  'Santander',
  'Sucre',
  'Tolima',
  'Valle del Cauca',
  'Vaupés',
  'Vichada',
];

final Map<String, List<String>> citiesMap = {
  'Bogotá D.C.': <String>[
    'Bogotá D.C.',
  ],
  'Amazonas': <String>[
    'El Encanto',
    'La Chorrera',
    'La Pedrera',
    'La Victoria',
    'Leticia',
    'Miriti Paraná',
    'Puerto Alegría',
    'Puerto Arica',
    'Puerto Nariño',
    'Puerto Santander',
    'Tarapacá',
  ],
  'Antioquia': <String>[
    'Abejorral',
    'Abriaquí',
    'Alejandría',
    'Amagá',
    'Amalfi',
    'Andes',
    'Angelópolis',
    'Angostura',
    'Anorí',
    'Anza',
    'Apartadó',
    'Arboletes',
    'Argelia',
    'Armenia',
    'Barbosa',
    'Bello',
    'Belmira',
    'Betania',
    'Betulia',
    'Briceño',
    'Buriticá',
    'Caicedo',
    'Caldas',
    'Campamento',
    'Caracolí',
    'Caramanta',
    'Carepa',
    'Carolina',
    'Caucasia',
    'Cañasgordas',
    'Chigorodó',
    'Cisneros',
    'Ciudad Bolívar',
    'Cocorná',
    'Concepción',
    'Concordia',
    'Copacabana',
    'Cáceres',
    'Dabeiba',
    'Don Matías',
    'Ebéjico',
    'El Bagre',
    'El Carmen de Viboral',
    'El Santuario',
    'Entrerrios',
    'Envigado',
    'Fredonia',
    'Frontino',
    'Giraldo',
    'Girardota',
    'Granada',
    'Guadalupe',
    'Guarne',
    'Guatapé',
    'Gómez Plata',
    'Heliconia',
    'Hispania',
    'Itagui',
    'Ituango',
    'Jardín',
    'Jericó',
    'La Ceja',
    'La Estrella',
    'La Pintada',
    'La Unión',
    'Liborina',
    'Maceo',
    'Marinilla',
    'Medellín',
    'Montebello',
    'Murindó',
    'Mutatá',
    'Nariño',
    'Nechí',
    'Necoclí',
    'Olaya',
    'Peque',
    'Peñol',
    'Pueblorrico',
    'Puerto Berrío',
    'Puerto Nare',
    'Puerto Triunfo',
    'Remedios',
    'Retiro',
    'Rionegro',
    'Sabanalarga',
    'Sabaneta',
    'Salgar',
    'San Andrés de Cuerquía',
    'San Carlos',
    'San Francisco',
    'San Jerónimo',
    'San José de La Montaña',
    'San Juan de Urabá',
    'San Luis',
    'San Pedro',
    'San Pedro de Uraba',
    'San Rafael',
    'San Roque',
    'San Vicente',
    'Santa Bárbara',
    'Santa Rosa de Osos',
    'Santafé de Antioquia',
    'Santo Domingo',
    'Segovia',
    'Sonsón',
    'Sopetrán',
    'Tarazá',
    'Tarso',
    'Titiribí',
    'Toledo',
    'Turbo',
    'Támesis',
    'Uramita',
    'Urrao',
    'Valdivia',
    'Valparaíso',
    'Vegachí',
    'Venecia',
    'Vigía del Fuerte',
    'Yalí',
    'Yarumal',
    'Yolombó',
    'Yondó',
    'Zaragoza',
  ],
  'Arauca': <String>[
    'Arauca',
    'Arauquita',
    'Cravo Norte',
    'Fortul',
    'Puerto Rondón',
    'Saravena',
    'Tame',
  ],
  'Atlántico': <String>[
    'Baranoa',
    'Barranquilla',
    'Campo de La Cruz',
    'Candelaria',
    'Galapa',
    'Juan de Acosta',
    'Luruaco',
    'Malambo',
    'Manatí',
    'Palmar de Varela',
    'Piojó',
    'Polonuevo',
    'Ponedera',
    'Puerto Colombia',
    'Repelón',
    'Sabanagrande',
    'Sabanalarga',
    'Santa Lucía',
    'Santo Tomás',
    'Soledad',
    'Suan',
    'Tubará',
    'Usiacurí',
  ],
  'Bolívar': <String>[
    'Achí',
    'Altos del Rosario',
    'Arenal',
    'Arjona',
    'Arroyohondo',
    'Barranco de Loba',
    'Calamar',
    'Cantagallo',
    'Cartagena',
    'Cicuco',
    'Clemencia',
    'Córdoba',
    'El Carmen de Bolívar',
    'El Guamo',
    'El Peñón',
    'Hatillo de Loba',
    'Magangué',
    'Mahates',
    'Margarita',
    'María la Baja',
    'Mompós',
    'Montecristo',
    'Morales',
    'Norosí',
    'Pinillos',
    'Regidor',
    'Río Viejo',
    'San Cristóbal',
    'San Estanislao',
    'San Fernando',
    'San Jacinto',
    'San Jacinto del Cauca',
    'San Juan Nepomuceno',
    'San Martín de Loba',
    'San Pablo de Borbur',
    'Santa Catalina',
    'Santa Rosa',
    'Santa Rosa del Sur',
    'Simití',
    'Soplaviento',
    'Talaigua Nuevo',
    'Tiquisio',
    'Turbaco',
    'Turbaná',
    'Villanueva',
    'Zambrano',
  ],
  'Boyacá': <String>[
    'Almeida',
    'Aquitania',
    'Arcabuco',
    'Belén',
    'Berbeo',
    'Betéitiva',
    'Boavita',
    'Boyacá',
    'Briceño',
    'Buena Vista',
    'Busbanzá',
    'Caldas',
    'Campohermoso',
    'Cerinza',
    'Chinavita',
    'Chiquinquirá',
    'Chiscas',
    'Chita',
    'Chitaraque',
    'Chivatá',
    'Chivor',
    'Chíquiza',
    'Ciénega',
    'Coper',
    'Corrales',
    'Covarachía',
    'Cubará',
    'Cucaita',
    'Cuítiva',
    'Cómbita',
    'Duitama',
    'El Cocuy',
    'El Espino',
    'Firavitoba',
    'Floresta',
    'Gachantivá',
    'Gameza',
    'Garagoa',
    'Guacamayas',
    'Guateque',
    'Guayatá',
    'Güicán',
    'Iza',
    'Jenesano',
    'Jericó',
    'La Capilla',
    'La Uvita',
    'La Victoria',
    'Labranzagrande',
    'Macanal',
    'Maripí',
    'Miraflores',
    'Mongua',
    'Monguí',
    'Moniquirá',
    'Motavita',
    'Muzo',
    'Nobsa',
    'Nuevo Colón',
    'Oicatá',
    'Otanche',
    'Pachavita',
    'Paipa',
    'Pajarito',
    'Panqueba',
    'Pauna',
    'Paya',
    'Paz de Río',
    'Pesca',
    'Pisba',
    'Puerto Boyacá',
    'Páez',
    'Quípama',
    'Ramiriquí',
    'Rondón',
    'Ráquira',
    'Saboyá',
    'Samacá',
    'San Eduardo',
    'San José de Pare',
    'San Luis de Gaceno',
    'San Mateo',
    'San Miguel de Sema',
    'San Pablo de Borbur',
    'Santa María',
    'Santa Rosa de Viterbo',
    'Santa Sofía',
    'Santana',
    'Sativanorte',
    'Sativasur',
    'Siachoque',
    'Soatá',
    'Socha',
    'Socotá',
    'Sogamoso',
    'Somondoco',
    'Sora',
    'Soracá',
    'Sotaquirá',
    'Susacón',
    'Sutamarchán',
    'Sutatenza',
    'Sáchica',
    'Tasco',
    'Tenza',
    'Tibaná',
    'Tibasosa',
    'Tinjacá',
    'Tipacoque',
    'Toca',
    'Togüí',
    'Tota',
    'Tunja',
    'Tununguá',
    'Turmequé',
    'Tuta',
    'Tutazá',
    'Tópaga',
    'Umbita',
    'Ventaquemada',
    'Villa de Leyva',
    'Viracachá',
    'Zetaquira',
  ],
  'Caldas': <String>[
    'Aguadas',
    'Anserma',
    'Aranzazu',
    'Belalcázar',
    'Chinchiná',
    'Filadelfia',
    'La Dorada',
    'La Merced',
    'Manizales',
    'Manzanares',
    'Marmato',
    'Marquetalia',
    'Marulanda',
    'Neira',
    'Norcasia',
    'Palestina',
    'Pensilvania',
    'Pácora',
    'Riosucio',
    'Risaralda',
    'Salamina',
    'Samaná',
    'San José',
    'Supía',
    'Victoria',
    'Villamaría',
    'Viterbo',
  ],
  'Caquetá': <String>[
    'Albania',
    'Belén de Los Andaquies',
    'Cartagena del Chairá',
    'Curillo',
    'El Doncello',
    'El Paujil',
    'Florencia',
    'La Montañita',
    'Milán',
    'Morelia',
    'Puerto Rico',
    'San José del Fragua',
    'San Vicente del Caguán',
    'Solano',
    'Solita',
    'Valparaíso',
  ],
  'Casanare': <String>[
    'Aguazul',
    'Chámeza',
    'Hato Corozal',
    'La Salina',
    'Maní',
    'Monterrey',
    'Nunchía',
    'Orocué',
    'Paz de Ariporo',
    'Pore',
    'Recetor',
    'Sabanalarga',
    'San Luis de Gaceno',
    'Sácama',
    'Tauramena',
    'Trinidad',
    'Támara',
    'Villanueva',
    'Yopal',
  ],
  'Cauca': <String>[
    'Almaguer',
    'Argelia',
    'Balboa',
    'Bolívar',
    'Buenos Aires',
    'Cajibío',
    'Caldono',
    'Caloto',
    'Corinto',
    'El Tambo',
    'Florencia',
    'Guachené',
    'Guapi',
    'Inzá',
    'Jambaló',
    'La Sierra',
    'La Vega',
    'López',
    'Mercaderes',
    'Miranda',
    'Morales',
    'Padilla',
    'Patía',
    'Piamonte',
    'Piendamó',
    'Popayán',
    'Puerto Tejada',
    'Puracé',
    'Páez',
    'Rosas',
    'San Sebastián',
    'Santa Rosa',
    'Santander de Quilichao',
    'Silvia',
    'Sotara',
    'Sucre',
    'Suárez',
    'Timbiquí',
    'Timbío',
    'Toribio',
    'Totoró',
    'Villa Rica',
  ],
  'Cesar': <String>[
    'Aguachica',
    'Agustín Codazzi',
    'Astrea',
    'Becerril',
    'Bosconia',
    'Chimichagua',
    'Chiriguaná',
    'Curumaní',
    'El Copey',
    'El Paso',
    'Gamarra',
    'González',
    'La Gloria',
    'La Jagua de Ibirico',
    'La Paz',
    'Manaure',
    'Pailitas',
    'Pelaya',
    'Pueblo Bello',
    'Río de Oro',
    'San Alberto',
    'San Diego',
    'San Martín',
    'Tamalameque',
    'Valledupar',
  ],
  'Chocó': <String>[
    'Acandí',
    'Alto Baudo',
    'Atrato',
    'Bagadó',
    'Bahía Solano',
    'Bajo Baudó',
    'Belén de Bajira',
    'Bojaya',
    'Carmen del Darien',
    'Condoto',
    'Cértegui',
    'El Cantón del San Pablo',
    'El Carmen de Atrato',
    'El Litoral del San Juan',
    'Istmina',
    'Juradó',
    'Lloró',
    'Medio Atrato',
    'Medio Baudó',
    'Medio San Juan',
    'Nuquí',
    'Nóvita',
    'Quibdó',
    'Riosucio',
    'Río Iro',
    'Río Quito',
    'San José del Palmar',
    'Sipí',
    'Tadó',
    'Unguía',
    'Unión Panamericana',
  ],
  'Córdoba': <String>[
    'Ayapel',
    'Buenavista',
    'Canalete',
    'Cereté',
    'Chimá',
    'Chinú',
    'Ciénaga de Oro',
    'Cotorra',
    'La Apartada',
    'Lorica',
    'Los Córdobas',
    'Momil',
    'Montelíbano',
    'Montería',
    'Moñitos',
    'Planeta Rica',
    'Pueblo Nuevo',
    'Puerto Escondido',
    'Puerto Libertador',
    'Purísima',
    'Sahagún',
    'San Andrés Sotavento',
    'San Antero',
    'San Bernardo del Viento',
    'San Carlos',
    'San José de Uré',
    'San Pelayo',
    'Tierralta',
    'Tuchín',
    'Valencia',
  ],
  'Cundinamarca': <String>[
    'Agua de Dios',
    'Albán',
    'Anapoima',
    'Anolaima',
    'Apulo',
    'Arbeláez',
    'Beltrán',
    'Bituima',
    'Bojacá',
    'Cabrera',
    'Cachipay',
    'Cajicá',
    'Caparrapí',
    'Caqueza',
    'Carmen de Carupa',
    'Chaguaní',
    'Chipaque',
    'Choachí',
    'Chocontá',
    'Chía',
    'Cogua',
    'Cota',
    'Cucunubá',
    'El Colegio',
    'El Peñón',
    'El Rosal',
    'Facatativá',
    'Fomeque',
    'Fosca',
    'Funza',
    'Fusagasugá',
    'Fúquene',
    'Gachala',
    'Gachancipá',
    'Gachetá',
    'Gama',
    'Girardot',
    'Granada',
    'Guachetá',
    'Guaduas',
    'Guasca',
    'Guataquí',
    'Guatavita',
    'Guayabal de Siquima',
    'Guayabetal',
    'Gutiérrez',
    'Jerusalén',
    'Junín',
    'La Calera',
    'La Mesa',
    'La Palma',
    'La Peña',
    'La Vega',
    'Lenguazaque',
    'Macheta',
    'Madrid',
    'Manta',
    'Medina',
    'Mosquera',
    'Nariño',
    'Nemocón',
    'Nilo',
    'Nimaima',
    'Nocaima',
    'Pacho',
    'Paime',
    'Pandi',
    'Paratebueno',
    'Pasca',
    'Puerto Salgar',
    'Pulí',
    'Quebradanegra',
    'Quetame',
    'Quipile',
    'Ricaurte',
    'San Antonio del Tequendama',
    'San Bernardo',
    'San Cayetano',
    'San Francisco',
    'San Juan de Río Seco',
    'Sasaima',
    'Sesquilé',
    'Sibaté',
    'Silvania',
    'Simijaca',
    'Soacha',
    'Sopó',
    'Subachoque',
    'Suesca',
    'Supatá',
    'Susa',
    'Sutatausa',
    'Tabio',
    'Tausa',
    'Tena',
    'Tenjo',
    'Tibacuy',
    'Tibirita',
    'Tocaima',
    'Tocancipá',
    'Topaipí',
    'Ubalá',
    'Ubaque',
    'Une',
    'Venecia',
    'Vergara',
    'Vianí',
    'Villa de San Diego de Ubaté',
    'Villagómez',
    'Villapinzón',
    'Villeta',
    'Viotá',
    'Yacopí',
    'Zipacón',
    'Zipaquirá',
    'Útica',
  ],
  'Guainía': <String>[
    'Barranco Minas',
    'Cacahual',
    'Inírida',
    'La Guadalupe',
    'Mapiripana',
    'Morichal',
    'Pana Pana',
    'Puerto Colombia',
    'San Felipe',
  ],
  'Guaviare': <String>[
    'Calamar',
    'El Retorno',
    'Miraflores',
    'San José del Guaviare',
  ],
  'Huila': <String>[
    'Acevedo',
    'Agrado',
    'Aipe',
    'Algeciras',
    'Altamira',
    'Baraya',
    'Campoalegre',
    'Colombia',
    'Elías',
    'Garzón',
    'Gigante',
    'Guadalupe',
    'Hobo',
    'Iquira',
    'Isnos',
    'La Argentina',
    'La Plata',
    'Neiva',
    'Nátaga',
    'Oporapa',
    'Paicol',
    'Palermo',
    'Palestina',
    'Pital',
    'Pitalito',
    'Rivera',
    'Saladoblanco',
    'San Agustín',
    'Santa María',
    'Suaza',
    'Tarqui',
    'Tello',
    'Teruel',
    'Tesalia',
    'Timaná',
    'Villavieja',
    'Yaguará',
  ],
  'La Guajira': <String>[
    'Albania',
    'Barrancas',
    'Dibula',
    'Distracción',
    'El Molino',
    'Fonseca',
    'Hatonuevo',
    'La Jagua del Pilar',
    'Maicao',
    'Manaure',
    'Riohacha',
    'San Juan del Cesar',
    'Uribia',
    'Urumita',
    'Villanueva',
  ],
  'Magdalena': <String>[
    'Algarrobo',
    'Aracataca',
    'Ariguaní',
    'Cerro San Antonio',
    'Chivolo',
    'Ciénaga',
    'Concordia',
    'El Banco',
    'El Piñon',
    'El Retén',
    'Fundación',
    'Guamal',
    'Nueva Granada',
    'Pedraza',
    'Pijiño del Carmen',
    'Pivijay',
    'Plato',
    'Pueblo Viejo',
    'Remolino',
    'Sabanas de San Angel',
    'Salamina',
    'San Sebastián de Buenavista',
    'San Zenón',
    'Santa Ana',
    'Santa Bárbara de Pinto',
    'Santa Marta',
    'Sitionuevo',
    'Tenerife',
    'Zapayán',
    'Zona Bananera',
  ],
  'Meta': <String>[
    'Acacias',
    'Barranca de Upía',
    'Cabuyaro',
    'Castilla la Nueva',
    'Cubarral',
    'Cumaral',
    'El Calvario',
    'El Castillo',
    'El Dorado',
    'Fuente de Oro',
    'Granada',
    'Guamal',
    'La Macarena',
    'Lejanías',
    'Mapiripán',
    'Mesetas',
    'Puerto Concordia',
    'Puerto Gaitán',
    'Puerto Lleras',
    'Puerto López',
    'Puerto Rico',
    'Restrepo',
    'San Carlos de Guaroa',
    'San Juan de Arama',
    'San Juanito',
    'San Martín',
    'Uribe',
    'Villavicencio',
    'Vista Hermosa',
  ],
  'Nariño': <String>[
    'Albán',
    'Aldana',
    'Ancuyá',
    'Arboleda',
    'Barbacoas',
    'Belén',
    'Buesaco',
    'Chachagüí',
    'Colón',
    'Consaca',
    'Contadero',
    'Cuaspud',
    'Cumbal',
    'Cumbitara',
    'Córdoba',
    'El Charco',
    'El Peñol',
    'El Rosario',
    'El Tablón de Gómez',
    'El Tambo',
    'Francisco Pizarro',
    'Funes',
    'Guachucal',
    'Guaitarilla',
    'Gualmatán',
    'Iles',
    'Imués',
    'Ipiales',
    'La Cruz',
    'La Florida',
    'La Llanada',
    'La Tola',
    'La Unión',
    'Leiva',
    'Linares',
    'Los Andes',
    'Magüí',
    'Mallama',
    'Mosquera',
    'Nariño',
    'Olaya Herrera',
    'Ospina',
    'Pasto',
    'Policarpa',
    'Potosí',
    'Providencia',
    'Puerres',
    'Pupiales',
    'Ricaurte',
    'Roberto Payán',
    'Samaniego',
    'San Andrés de Tumaco',
    'San Bernardo',
    'San Lorenzo',
    'San Pablo',
    'San Pedro de Cartago',
    'Sandoná',
    'Santa Bárbara',
    'Santacruz',
    'Sapuyes',
    'Taminango',
    'Tangua',
    'Túquerres',
    'Yacuanquer',
  ],
  'Norte de Santander': <String>[
    'Abrego',
    'Arboledas',
    'Bochalema',
    'Bucarasica',
    'Cachirá',
    'Chinácota',
    'Chitagá',
    'Convención',
    'Cucutilla',
    'Cácota',
    'Cúcuta',
    'Durania',
    'El Carmen',
    'El Tarra',
    'El Zulia',
    'Gramalote',
    'Hacarí',
    'Herrán',
    'La Esperanza',
    'La Playa',
    'Labateca',
    'Los Patios',
    'Lourdes',
    'Mutiscua',
    'Ocaña',
    'Pamplona',
    'Pamplonita',
    'Puerto Santander',
    'Ragonvalia',
    'Salazar',
    'San Calixto',
    'San Cayetano',
    'Santiago',
    'Sardinata',
    'Silos',
    'Teorama',
    'Tibú',
    'Toledo',
    'Villa Caro',
    'Villa del Rosario',
  ],
  'Putumayo': <String>[
    'Colón',
    'Leguízamo',
    'Mocoa',
    'Orito',
    'Puerto Asís',
    'Puerto Caicedo',
    'Puerto Guzmán',
    'San Francisco',
    'San Miguel',
    'Santiago',
    'Sibundoy',
    'Valle de Guamez',
    'Villagarzón',
  ],
  'Quindío': <String>[
    'Armenia',
    'Buenavista',
    'Calarcá',
    'Circasia',
    'Córdoba',
    'Filandia',
    'Génova',
    'La Tebaida',
    'Montenegro',
    'Pijao',
    'Quimbaya',
    'Salento',
  ],
  'Risaralda': <String>[
    'Apía',
    'Balboa',
    'Belén de Umbría',
    'Dosquebradas',
    'Guática',
    'La Celia',
    'La Virginia',
    'Marsella',
    'Mistrató',
    'Pereira',
    'Pueblo Rico',
    'Quinchía',
    'Santa Rosa de Cabal',
    'Santuario',
  ],
  'San Andrés y Providencia': <String>[
    'Providencia',
    'San Andrés',
  ],
  'Santander': <String>[
    'Aguada',
    'Albania',
    'Aratoca',
    'Barbosa',
    'Barichara',
    'Barrancabermeja',
    'Betulia',
    'Bolívar',
    'Bucaramanga',
    'Cabrera',
    'California',
    'Capitanejo',
    'Carcasí',
    'Cepitá',
    'Cerrito',
    'Charalá',
    'Charta',
    'Chimá',
    'Chipatá',
    'Cimitarra',
    'Concepción',
    'Confines',
    'Contratación',
    'Coromoro',
    'Curití',
    'El Carmen de Chucurí',
    'El Guacamayo',
    'El Peñón',
    'El Playón',
    'Encino',
    'Enciso',
    'Floridablanca',
    'Florián',
    'Galán',
    'Gambita',
    'Girón',
    'Guaca',
    'Guadalupe',
    'Guapotá',
    'Guavatá',
    'Güepsa',
    'Hato',
    'Jesús María',
    'Jordán',
    'La Belleza',
    'La Paz',
    'Landázuri',
    'Lebríja',
    'Los Santos',
    'Macaravita',
    'Matanza',
    'Mogotes',
    'Molagavita',
    'Málaga',
    'Ocamonte',
    'Oiba',
    'Onzaga',
    'Palmar',
    'Palmas del Socorro',
    'Piedecuesta',
    'Pinchote',
    'Puente Nacional',
    'Puerto Parra',
    'Puerto Wilches',
    'Páramo',
    'Rionegro',
    'Sabana de Torres',
    'San Andrés',
    'San Benito',
    'San Gil',
    'San Joaquín',
    'San José de Miranda',
    'San Miguel',
    'San Vicente de Chucurí',
    'Santa Bárbara',
    'Santa Helena del Opón',
    'Simacota',
    'Socorro',
    'Suaita',
    'Sucre',
    'Suratá',
    'Tona',
    'Valle de San José',
    'Vetas',
    'Villanueva',
    'Vélez',
    'Zapatoca',
  ],
  'Sucre': <String>[
    'Buenavista',
    'Caimito',
    'Chalán',
    'Coloso',
    'Corozal',
    'Coveñas',
    'El Roble',
    'Galeras',
    'Guaranda',
    'La Unión',
    'Los Palmitos',
    'Majagual',
    'Morroa',
    'Ovejas',
    'Palmito',
    'Sampués',
    'San Benito Abad',
    'San Juan de Betulia',
    'San Luis de Sincé',
    'San Marcos',
    'San Onofre',
    'San Pedro',
    'Santiago de Tolú',
    'Sincelejo',
    'Sucre',
    'Tolú Viejo',
  ],
  'Tolima': <String>[
    'Alpujarra',
    'Alvarado',
    'Ambalema',
    'Anzoátegui',
    'Armero',
    'Ataco',
    'Cajamarca',
    'Carmen de Apicala',
    'Casabianca',
    'Chaparral',
    'Coello',
    'Coyaima',
    'Cunday',
    'Dolores',
    'Espinal',
    'Falan',
    'Flandes',
    'Fresno',
    'Guamo',
    'Herveo',
    'Honda',
    'Ibagué',
    'Icononzo',
    'Lérida',
    'Líbano',
    'Mariquita',
    'Melgar',
    'Murillo',
    'Natagaima',
    'Ortega',
    'Palocabildo',
    'Piedras',
    'Planadas',
    'Prado',
    'Purificación',
    'Rio Blanco',
    'Roncesvalles',
    'Rovira',
    'Saldaña',
    'San Antonio',
    'San Luis',
    'Santa Isabel',
    'Suárez',
    'Valle de San Juan',
    'Venadillo',
    'Villahermosa',
    'Villarrica',
  ],
  'Valle del Cauca': <String>[
    'Alcalá',
    'Andalucía',
    'Ansermanuevo',
    'Argelia',
    'Bolívar',
    'Buenaventura',
    'Bugalagrande',
    'Caicedonia',
    'Cali',
    'Calima',
    'Candelaria',
    'Cartago',
    'Dagua',
    'El Cairo',
    'El Cerrito',
    'El Dovio',
    'El Águila',
    'Florida',
    'Ginebra',
    'Guacarí',
    'Guadalajara de Buga',
    'Jamundí',
    'La Cumbre',
    'La Unión',
    'La Victoria',
    'Obando',
    'Palmira',
    'Pradera',
    'Restrepo',
    'Riofrío',
    'Roldanillo',
    'San Pedro',
    'Sevilla',
    'Toro',
    'Trujillo',
    'Tuluá',
    'Ulloa',
    'Versalles',
    'Vijes',
    'Yotoco',
    'Yumbo',
    'Zarzal',
  ],
  'Vaupés': <String>[
    'Caruru',
    'Mitú',
    'Pacoa',
    'Papunaua',
    'Taraira',
    'Yavaraté',
  ],
  'Vichada': <String>[
    'Cumaribo',
    'La Primavera',
    'Puerto Carreño',
    'Santa Rosalía',
  ],
};